# Generated by Django 3.2.10 on 2022-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_form', '0002_alter_details_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='details',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
